config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#index"
  resources :schemas, only: [:index, :show]

  resources :inspirations, only: [:index, :show]

  scope "products", controller: "products" do
    root action: "index", as: :products
    get "grouped_by/:id", :action => "grouped_by", as: "grouped_products"
    get ":id", action: :show, as: "product"
  end

  scope "shares", controller: "shares" do
    root action: "index", as: :shares
    get "hot/:id", :action => "grouped_by"
    get ":id", action: :show, as: "share"
  end

  resources :articles, only: [:index, :show]

  post "/places/update_place", to: "places#set_place", as: :update_place

  scope "about", controller: "abouts" do
    root action: "index", :as => "about_root"
    get ":id", action: "show", :as => "about"
  end
  controller "pages" do

    get "contacts", :action => "contacts"
  end








  match "*args", to: "application#render_not_found", as: "not_found", via: [:get, :post, :update, :create, :put, :delete]

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible *attribute_names

  #cattr_reader :per_page
  #@@per_page = 10
  paginates_per 10

  has_many :places
  has_and_belongs_to_many :groups
  has_many :images, :as => :imageable
  attr_accessible :places, :place_ids
  attr_accessible :groups, :group_ids
  attr_accessible :images, :image_ids

  image :avatar, styles: { admin_thumb: "100x50#", thumb: "300x122#" }

  image :logo

  #validates_attachment_presence :logo
  #validates_attachment_content_type :logo, :content_type => 'image/png', :unless => Proc.new { |p| p.logo_file_name.blank? }



  scope :published, -> { where(published: true) }

  validates_presence_of :name, :brief, :description


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  def index
    @title = "КАТАЛОГ"
    @products = Product.published.page(params[:page])
    # unless @products.nil?
    #   @products = @products.force_encoding("utf-8")
    # end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  def grouped_by
    @title = "КАТАЛОГ"
    begin
      @group = Group.published.find(params[:id])
    rescue
      return render_not_found
    end
    @products = Product.published.joins(:groups).page(params[:page])

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    begin
      @product = Product.published.find(params[:id])
    rescue
      return render_not_found
    end
    @title = "КАТАЛОГ // #{@product.name}"
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_catalogue.html.erb
<div class="span-4">
  <%= content_tag("h1", "Каталог", :class => "title") %>
  <div class="padd">
    <ul id="content_menu">
      <% Group.published.roots.each do |group| %>
        <% if group == main_group || (main_group && main_group.ancestors.include?(group)) %>
        <li class="active">
          <%= link_to group.name.force_encoding("utf-8"), grouped_products_path(group) %>
        <% else %>
        <li>
          <%= link_to group.name.force_encoding("utf-8"), grouped_products_path(group) %>
        <% end %>
          <% unless group.children.published.blank? %>
            <ul>
              <% group.children.published.each do |child| %>
              <li class="<%= child == main_group ? 'active' : '' %>"><%= link_to child.name.force_encoding("utf-8"),  grouped_products_path(child) %></li>
              <% end %>
            </ul>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<br /> <br />
<iframe style="margin-top: 2px;" width="280" height="280" src="http://www.youtube.com/embed/O_16bQ1o-Tw" frameborder="0" allowfullscreen></iframe> <br /> <br /> <iframe width="280" height="280" src="//www.youtube.com/embed/9O9CmyaRLUI" frameborder="0" allowfullscreen></iframe>
</div>

app/views/products/index.html.erb
<%= render :partial => "/products/catalogue", :locals => {:main_group => @group} %>
<div class="span-8 last">
  <div class="padd">
    <%= content_tag("h1", "Перелік компаній", :class => "color-title") %>
  </div>
  <div class="articles">
    <% @products.each do |product| %>
        <div class="article">
          <div class="span-7 last">
            <div class="padd with_logo">
              <%= link_to content_tag("h3", product.name.force_encoding("utf-8")), product, :title => product.name.force_encoding("utf-8") %>
              <%= image_tag product.logo.url.force_encoding("utf-8"), :alt => "Логотип...", :title => product.name.force_encoding("utf-8"), :class => "p_logo"  %>
            </div>
          </div>
          <div class="span-7 last">
            <div class="span-4">
              <%= link_to image_tag(product.avatar.url(:thumb).force_encoding("utf-8"), :alt => product.name.force_encoding("utf-8")), product, :title => product.name.force_encoding("utf-8"), :class => "with_img" %>
            </div>
            <div class="span-3 last">
              <i class="longer product"><%= truncate(product.brief.force_encoding("utf-8"), :length => 200) %></i>
              <%= link_to "Деталі", product, :title => "Деталі", :class => "details" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  <%= paginate(@products, :previous_label => "<< Попередня", :next_label => "Наступна >>") %>
</div>

app/views/products/show.html.erb
<link rel="stylesheet" href="/stylesheets/jquery.ad-gallery.css" type="text/css" media="screen, projection"/>
<script type="text/javascript" src="/javascripts/jquery.ad-gallery.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    var gallery = $('.ad-gallery').adGallery({slideshow:{enable: false}});
  });
</script>
<div class="span-4">
  <%= render :partial => "catalogue", :locals => { :main_group => @product.groups.first } %>
</div>
<div class="span-8 last">
  <div class="padd">
    <%= content_tag("h1", @product.name.force_encoding("utf-8"), :class => "color-title") %>
  </div>
  <% unless @product.images.blank? %>
  <div class="ad-gallery">
    <div class="ad-image-wrapper">
    </div>
    <div class="ad-controls">
    </div>
    <div class="ad-nav">
      <div class="ad-thumbs">
        <ul class="ad-thumb-list">
          <% @product.images.each_with_index do |image, index| %>
            <li>
              <%= link_to image_tag(image.avatar.url(:gallery_thumb).force_encoding("utf-8"), :title => image.name.force_encoding("utf-8"), :alt => @product.name.force_encoding("utf-8"), :class => "image#{index}"), image.avatar.url.force_encoding("utf-8") %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <% end %>
  <div class="padd">
    <%= @product.description.html_safe.force_encoding("utf-8") %>
  </div>
</div>