config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#index"
  resources :schemas, only: [:index, :show]

  resources :inspirations, only: [:index, :show]

  scope "products", controller: "products" do
    root action: "index", as: :products
    get "grouped_by/:id", :action => "grouped_by", as: "grouped_products"
    get ":id", action: :show, as: "product"
  end

  scope "shares", controller: "shares" do
    root action: "index", as: :shares
    get "hot/:id", :action => "grouped_by"
    get ":id", action: :show, as: "share"
  end

  resources :articles, only: [:index, :show]

  post "/places/update_place", to: "places#set_place", as: :update_place

  scope "about", controller: "abouts" do
    root action: "index", :as => "about_root"
    get ":id", action: "show", :as => "about"
  end
  controller "pages" do

    get "contacts", :action => "contacts"
  end








  match "*args", to: "application#render_not_found", as: "not_found", via: [:get, :post, :update, :create, :put, :delete]

end

app/models/schema.rb
class Schema < ActiveRecord::Base
  attr_accessible *attribute_names

  image :avatar, :styles => { :thumb => "620x>" }


  scope :published, -> { where(published: true) }
  has_many :places
  attr_accessible :places, :place_ids
  has_many :products, :through => :places
  attr_accessible :products, :product_ids
  validates_presence_of :name
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController
  before_filter :preload_schemas
  
  def index
    
  end
  
  def show
    begin
      @schema = Schema.published.find(params[:id])
    rescue
      return render_not_found
    end
    @places = @schema.places.order("name ASC")
  end
  
  private
  
  def preload_schemas
    @schemas = Schema.published.all
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper
end

app/views/schemas/index.html.erb
<script type="text/javascript"></script>
<div class="span-4">
  <%= content_tag("h1", "План схема", :class => "title") %>
  <div class="padd">
    <ul id="content_menu">
    	<% @schemas.each do |schema| %>
	      	<li>
	          <%= link_to schema.name, schema %>
	        </li>
        <% end %>
    </ul>
  </div>
  <div class="clear"></div>
<br /> <br />
<iframe style="margin-top: 2px;" width="280" height="280" src="http://www.youtube.com/embed/O_16bQ1o-Tw" frameborder="0" allowfullscreen></iframe><br /> <br /> <iframe width="280" height="280" src="//www.youtube.com/embed/9O9CmyaRLUI" frameborder="0" allowfullscreen></iframe>

</div>

<div class="span-8 realtive last">

</div>

app/views/schemas/show.html.erb
<% unless session[:typus_user_id].blank? %>
<script>
	$(function() {
		$( ".schema-items" ).draggable({
			stop: function() {
				var offset = $(this).position();
	            var xPos = offset.left;
	            var yPos = offset.top;
	            $.post('<%= update_place_path %>', { id: parseInt($(this).attr("id")), left: parseInt(xPos), top: parseInt(yPos) }, function() {});
			}
		});
	});
</script>
<% end %>
<div class="span-4">
	<%= content_tag("h1", "План схема", :class => "title") %>
	<div class="padd">
		<ul id="content_menu">
			<% @schemas.each do |schema| %>
			<% if schema == @schema %>
			<li class="active">
				<%= link_to schema.name.force_encoding("utf-8"), schema %>
			</li>
			<% else %>
			<li>
				<%= link_to schema.name.force_encoding("utf-8"), schema %>
			</li>
			<% end %>
			<% end %>
		</ul>
	</div>
	<div class="clear"></div>
	<br /> <br />
<iframe style="margin-top: 2px;" width="280" height="280" src="http://www.youtube.com/embed/O_16bQ1o-Tw" frameborder="0" allowfullscreen></iframe> <br /> <br /> <iframe width="280" height="280" src="//www.youtube.com/embed/9O9CmyaRLUI" frameborder="0" allowfullscreen></iframe>
</div>
<div class="span-8 realtive last">
	<div class="padd">
		<%= content_tag("h1", "Графічна план-схема", :class => "color-title") %>
		<%= content_tag("h3", @schema.name.force_encoding("utf-8"), :class => "floor") %>
	</div>
	<div class="schema">
		<%= image_tag @schema.avatar.url(:thumb).force_encoding("utf-8"), :alt => @schema.name.force_encoding("utf-8") %>

	</div>
</div>
<div class="span-12">
	<%= content_tag("h1", "Cписок орендарів", :class => "title") %>
	<%# @places.each do |place| %>

		<!-- <code>
			<pre><%#= place.inspect %></pre>
		</code> -->

	<%# end %>
	<% @places.each do |place| %>
			<%= link_to image_tag(place.product.logo.url().force_encoding("utf-8"), :alt => place.product.name.force_encoding("utf-8")), place.product, :class => "schema-items", :style => "position: initial !important; float: left; margin-right: 20px; margin-top: 20px;", :id => "#{place.id}_place" %>
		<% end %>
</div>